export const countries = [
  { country: "Tajikistan", slug: "tajikistan", ISO2: "TJ" },
  { country: "Togo", slug: "togo", ISO2: "TG" },
  { country: "Anguilla", slug: "anguilla", ISO2: "AI" },
  { country: "Finland", slug: "finland", ISO2: "FI" },
  { country: "Jordan", slug: "jordan", ISO2: "JO" },
  { country: "Botswana", slug: "botswana", ISO2: "BW" },
  { country: "Solomon Islands", slug: "solomon-islands", ISO2: "SB" },
  { country: "Trinidad and Tobago", slug: "trinidad-and-tobago", ISO2: "TT" },
  { country: "United States of America", slug: "united-states", ISO2: "US" },
  { country: "American Samoa", slug: "american-samoa", ISO2: "AS" },
  { country: "Côte d'Ivoire", slug: "cote-divoire", ISO2: "CI" },
  { country: "Djibouti", slug: "djibouti", ISO2: "DJ" },
  { country: "Swaziland", slug: "swaziland", ISO2: "SZ" },
  { country: "Viet Nam", slug: "vietnam", ISO2: "VN" },
  { country: "Gibraltar", slug: "gibraltar", ISO2: "GI" },
  { country: "Montenegro", slug: "montenegro", ISO2: "ME" },
  { country: "Pakistan", slug: "pakistan", ISO2: "PK" },
  { country: "Cambodia", slug: "cambodia", ISO2: "KH" },
  { country: "Nicaragua", slug: "nicaragua", ISO2: "NI" },
  { country: "Guinea", slug: "guinea", ISO2: "GN" },
  { country: "Switzerland", slug: "switzerland", ISO2: "CH" },
  { country: "Azerbaijan", slug: "azerbaijan", ISO2: "AZ" },
  { country: "Norfolk Island", slug: "norfolk-island", ISO2: "NF" },
  { country: "Sri Lanka", slug: "sri-lanka", ISO2: "LK" },
  { country: "Brunei Darussalam", slug: "brunei", ISO2: "BN" },
  { country: "Lebanon", slug: "lebanon", ISO2: "LB" },
  { country: "Liberia", slug: "liberia", ISO2: "LR" },
  { country: "Monaco", slug: "monaco", ISO2: "MC" },
  { country: "Taiwan, Republic of China", slug: "taiwan", ISO2: "TW" },
  { country: "ALA Aland Islands", slug: "ala-aland-islands", ISO2: "AX" },
  { country: "Bahrain", slug: "bahrain", ISO2: "BH" },
  { country: "Ukraine", slug: "ukraine", ISO2: "UA" },
  {
    country: "Saint-Martin (French part)",
    slug: "saint-martin-french-part",
    ISO2: "MF",
  },
  { country: "Venezuela (Bolivarian Republic)", slug: "venezuela", ISO2: "VE" },
  { country: "Myanmar", slug: "myanmar", ISO2: "MM" },
  { country: "New Caledonia", slug: "new-caledonia", ISO2: "NC" },
  { country: "Poland", slug: "poland", ISO2: "PL" },
  { country: "Argentina", slug: "argentina", ISO2: "AR" },
  { country: "Isle of Man", slug: "isle-of-man", ISO2: "IM" },
  { country: "Turkmenistan", slug: "turkmenistan", ISO2: "TM" },
  { country: "Saint-Barthélemy", slug: "saint-barthélemy", ISO2: "BL" },
  { country: "France", slug: "france", ISO2: "FR" },
  { country: "Ireland", slug: "ireland", ISO2: "IE" },
  { country: "Lesotho", slug: "lesotho", ISO2: "LS" },
  {
    country: "Holy See (Vatican City State)",
    slug: "holy-see-vatican-city-state",
    ISO2: "VA",
  },
  { country: "Suriname", slug: "suriname", ISO2: "SR" },
  { country: "Bouvet Island", slug: "bouvet-island", ISO2: "BV" },
  {
    country: "Heard and Mcdonald Islands",
    slug: "heard-and-mcdonald-islands",
    ISO2: "HM",
  },
  { country: "Namibia", slug: "namibia", ISO2: "NA" },
  { country: "Bolivia", slug: "bolivia", ISO2: "BO" },
  { country: "Honduras", slug: "honduras", ISO2: "HN" },
  { country: "Singapore", slug: "singapore", ISO2: "SG" },
  { country: "Jamaica", slug: "jamaica", ISO2: "JM" },
  { country: "Niger", slug: "niger", ISO2: "NE" },
  { country: "Cayman Islands", slug: "cayman-islands", ISO2: "KY" },
  { country: "Iraq", slug: "iraq", ISO2: "IQ" },
  { country: "Guinea-Bissau", slug: "guinea-bissau", ISO2: "GW" },
  { country: "New Zealand", slug: "new-zealand", ISO2: "NZ" },
  { country: "Aruba", slug: "aruba", ISO2: "AW" },
  { country: "Burkina Faso", slug: "burkina-faso", ISO2: "BF" },
  { country: "Iran, Islamic Republic of", slug: "iran", ISO2: "IR" },
  { country: "Kenya", slug: "kenya", ISO2: "KE" },
  { country: "Malaysia", slug: "malaysia", ISO2: "MY" },
  { country: "Romania", slug: "romania", ISO2: "RO" },
  { country: "Russian Federation", slug: "russia", ISO2: "RU" },
  { country: "Belize", slug: "belize", ISO2: "BZ" },
  { country: "Faroe Islands", slug: "faroe-islands", ISO2: "FO" },
  { country: "Tonga", slug: "tonga", ISO2: "TO" },
  {
    country: "Saint Pierre and Miquelon",
    slug: "saint-pierre-and-miquelon",
    ISO2: "PM",
  },
  {
    country: "Sao Tome and Principe",
    slug: "sao-tome-and-principe",
    ISO2: "ST",
  },
  {
    country: "Svalbard and Jan Mayen Islands",
    slug: "svalbard-and-jan-mayen-islands",
    ISO2: "SJ",
  },
  { country: "Belarus", slug: "belarus", ISO2: "BY" },
  { country: "Chile", slug: "chile", ISO2: "CL" },
  { country: "Eritrea", slug: "eritrea", ISO2: "ER" },
  { country: "Guyana", slug: "guyana", ISO2: "GY" },
  { country: "India", slug: "india", ISO2: "IN" },
  { country: "Barbados", slug: "barbados", ISO2: "BB" },
  { country: "Puerto Rico", slug: "puerto-rico", ISO2: "PR" },
  { country: "Indonesia", slug: "indonesia", ISO2: "ID" },
  { country: "Libya", slug: "libya", ISO2: "LY" },
  {
    country: "Micronesia, Federated States of",
    slug: "micronesia",
    ISO2: "FM",
  },
  { country: "Panama", slug: "panama", ISO2: "PA" },
  { country: "Moldova", slug: "moldova", ISO2: "MD" },
  { country: "Mexico", slug: "mexico", ISO2: "MX" },
  { country: "United Kingdom", slug: "united-kingdom", ISO2: "GB" },
  { country: "Armenia", slug: "armenia", ISO2: "AM" },
  { country: "Bahamas", slug: "bahamas", ISO2: "BS" },
  { country: "Germany", slug: "germany", ISO2: "DE" },
  { country: "Norway", slug: "norway", ISO2: "NO" },
  { country: "Equatorial Guinea", slug: "equatorial-guinea", ISO2: "GQ" },
  { country: "Estonia", slug: "estonia", ISO2: "EE" },
  { country: "Guadeloupe", slug: "guadeloupe", ISO2: "GP" },
  {
    country: "Saint Kitts and Nevis",
    slug: "saint-kitts-and-nevis",
    ISO2: "KN",
  },
  { country: "Western Sahara", slug: "western-sahara", ISO2: "EH" },
  { country: "Pitcairn", slug: "pitcairn", ISO2: "PN" },
  { country: "Rwanda", slug: "rwanda", ISO2: "RW" },
  { country: "Kyrgyzstan", slug: "kyrgyzstan", ISO2: "KG" },
  { country: "Macao, SAR China", slug: "macao-sar-china", ISO2: "MO" },
  { country: "Mali", slug: "mali", ISO2: "ML" },
  { country: "Slovenia", slug: "slovenia", ISO2: "SI" },
  { country: "Spain", slug: "spain", ISO2: "ES" },
  { country: "Cape Verde", slug: "cape-verde", ISO2: "CV" },
  { country: "Haiti", slug: "haiti", ISO2: "HT" },
  { country: "Gabon", slug: "gabon", ISO2: "GA" },
  { country: "Saint Lucia", slug: "saint-lucia", ISO2: "LC" },
  {
    country: "Central African Republic",
    slug: "central-african-republic",
    ISO2: "CF",
  },
  { country: "Ecuador", slug: "ecuador", ISO2: "EC" },
  { country: "Nigeria", slug: "nigeria", ISO2: "NG" },
  { country: "French Polynesia", slug: "french-polynesia", ISO2: "PF" },
  { country: "Palestinian Territory", slug: "palestine", ISO2: "PS" },
  { country: "Chad", slug: "chad", ISO2: "TD" },
  { country: "Marshall Islands", slug: "marshall-islands", ISO2: "MH" },
  { country: "Montserrat", slug: "montserrat", ISO2: "MS" },
  { country: "Niue", slug: "niue", ISO2: "NU" },
  { country: "Qatar", slug: "qatar", ISO2: "QA" },
  { country: "Bangladesh", slug: "bangladesh", ISO2: "BD" },
  { country: "Sudan", slug: "sudan", ISO2: "SD" },
  { country: "Sweden", slug: "sweden", ISO2: "SE" },
  { country: "Tanzania, United Republic of", slug: "tanzania", ISO2: "TZ" },
  { country: "Palau", slug: "palau", ISO2: "PW" },
  { country: "Zimbabwe", slug: "zimbabwe", ISO2: "ZW" },
  { country: "Algeria", slug: "algeria", ISO2: "DZ" },
  { country: "Uganda", slug: "uganda", ISO2: "UG" },
  { country: "Morocco", slug: "morocco", ISO2: "MA" },
  { country: "Timor-Leste", slug: "timor-leste", ISO2: "TL" },
  { country: "Czech Republic", slug: "czech-republic", ISO2: "CZ" },
  { country: "Latvia", slug: "latvia", ISO2: "LV" },
  {
    country: "French Southern Territories",
    slug: "french-southern-territories",
    ISO2: "TF",
  },
  { country: "Serbia", slug: "serbia", ISO2: "RS" },
  { country: "Tuvalu", slug: "tuvalu", ISO2: "TV" },
  { country: "Antigua and Barbuda", slug: "antigua-and-barbuda", ISO2: "AG" },
  { country: "Benin", slug: "benin", ISO2: "BJ" },
  { country: "Sierra Leone", slug: "sierra-leone", ISO2: "SL" },
  {
    country: "South Georgia and the South Sandwich Islands",
    slug: "south-georgia-and-the-south-sandwich-islands",
    ISO2: "GS",
  },
  { country: "Comoros", slug: "comoros", ISO2: "KM" },
  { country: "Japan", slug: "japan", ISO2: "JP" },
  {
    country: "Northern Mariana Islands",
    slug: "northern-mariana-islands",
    ISO2: "MP",
  },
  { country: "Greenland", slug: "greenland", ISO2: "GL" },
  { country: "Lao PDR", slug: "lao-pdr", ISO2: "LA" },
  { country: "Saudi Arabia", slug: "saudi-arabia", ISO2: "SA" },
  { country: "Senegal", slug: "senegal", ISO2: "SN" },
  { country: "Colombia", slug: "colombia", ISO2: "CO" },
  { country: "Congo (Brazzaville)", slug: "congo-brazzaville", ISO2: "CG" },
  { country: "Kuwait", slug: "kuwait", ISO2: "KW" },
  { country: "Martinique", slug: "martinique", ISO2: "MQ" },
  { country: "Oman", slug: "oman", ISO2: "OM" },
  { country: "Tokelau", slug: "tokelau", ISO2: "TK" },
  { country: "Angola", slug: "angola", ISO2: "AO" },
  { country: "Costa Rica", slug: "costa-rica", ISO2: "CR" },
  { country: "Grenada", slug: "grenada", ISO2: "GD" },
  { country: "Australia", slug: "australia", ISO2: "AU" },
  { country: "Israel", slug: "israel", ISO2: "IL" },
  { country: "Liechtenstein", slug: "liechtenstein", ISO2: "LI" },
  { country: "Austria", slug: "austria", ISO2: "AT" },
  { country: "Mauritius", slug: "mauritius", ISO2: "MU" },
  { country: "Yemen", slug: "yemen", ISO2: "YE" },
  { country: "Hong Kong, SAR China", slug: "hong-kong-sar-china", ISO2: "HK" },
  { country: "Kazakhstan", slug: "kazakhstan", ISO2: "KZ" },
  { country: "Syrian Arab Republic (Syria)", slug: "syria", ISO2: "SY" },
  { country: "Tunisia", slug: "tunisia", ISO2: "TN" },
  { country: "United Arab Emirates", slug: "united-arab-emirates", ISO2: "AE" },
  { country: "Afghanistan", slug: "afghanistan", ISO2: "AF" },
  { country: "Burundi", slug: "burundi", ISO2: "BI" },
  {
    country: "Wallis and Futuna Islands",
    slug: "wallis-and-futuna-islands",
    ISO2: "WF",
  },
  { country: "Dominica", slug: "dominica", ISO2: "DM" },
  { country: "Fiji", slug: "fiji", ISO2: "FJ" },
  { country: "French Guiana", slug: "french-guiana", ISO2: "GF" },
  { country: "Virgin Islands, US", slug: "virgin-islands", ISO2: "VI" },
  {
    country: "British Virgin Islands",
    slug: "british-virgin-islands",
    ISO2: "VG",
  },
  { country: "China", slug: "china", ISO2: "CN" },
  { country: "Cuba", slug: "cuba", ISO2: "CU" },
  { country: "Cyprus", slug: "cyprus", ISO2: "CY" },
  { country: "Dominican Republic", slug: "dominican-republic", ISO2: "DO" },
  { country: "Guernsey", slug: "guernsey", ISO2: "GG" },
  { country: "Maldives", slug: "maldives", ISO2: "MV" },
  { country: "Christmas Island", slug: "christmas-island", ISO2: "CX" },
  { country: "Réunion", slug: "réunion", ISO2: "RE" },
  { country: "Vanuatu", slug: "vanuatu", ISO2: "VU" },
  {
    country: "US Minor Outlying Islands",
    slug: "us-minor-outlying-islands",
    ISO2: "UM",
  },
  { country: "Bulgaria", slug: "bulgaria", ISO2: "BG" },
  {
    country: "Cocos (Keeling) Islands",
    slug: "cocos-keeling-islands",
    ISO2: "CC",
  },
  { country: "Uruguay", slug: "uruguay", ISO2: "UY" },
  { country: "Macedonia, Republic of", slug: "macedonia", ISO2: "MK" },
  { country: "Peru", slug: "peru", ISO2: "PE" },
  { country: "Philippines", slug: "philippines", ISO2: "PH" },
  { country: "Gambia", slug: "gambia", ISO2: "GM" },
  { country: "Iceland", slug: "iceland", ISO2: "IS" },
  { country: "Luxembourg", slug: "luxembourg", ISO2: "LU" },
  { country: "Ghana", slug: "ghana", ISO2: "GH" },
  { country: "Cook Islands", slug: "cook-islands", ISO2: "CK" },
  { country: "El Salvador", slug: "el-salvador", ISO2: "SV" },
  { country: "Georgia", slug: "georgia", ISO2: "GE" },
  { country: "Slovakia", slug: "slovakia", ISO2: "SK" },
  { country: "Somalia", slug: "somalia", ISO2: "SO" },
  { country: "Guam", slug: "guam", ISO2: "GU" },
  { country: "Papua New Guinea", slug: "papua-new-guinea", ISO2: "PG" },
  { country: "San Marino", slug: "san-marino", ISO2: "SM" },
  { country: "Samoa", slug: "samoa", ISO2: "WS" },
  { country: "Republic of Kosovo", slug: "kosovo", ISO2: "XK" },
  {
    country: "Bosnia and Herzegovina",
    slug: "bosnia-and-herzegovina",
    ISO2: "BA",
  },
  { country: "Congo (Kinshasa)", slug: "congo-kinshasa", ISO2: "CD" },
  { country: "Korea (North)", slug: "korea-north", ISO2: "KP" },
  { country: "Lithuania", slug: "lithuania", ISO2: "LT" },
  {
    country: "Saint Vincent and Grenadines",
    slug: "saint-vincent-and-the-grenadines",
    ISO2: "VC",
  },
  { country: "Zambia", slug: "zambia", ISO2: "ZM" },
  { country: "Bermuda", slug: "bermuda", ISO2: "BM" },
  { country: "Ethiopia", slug: "ethiopia", ISO2: "ET" },
  { country: "Madagascar", slug: "madagascar", ISO2: "MG" },
  { country: "Mayotte", slug: "mayotte", ISO2: "YT" },
  {
    country: "British Indian Ocean Territory",
    slug: "british-indian-ocean-territory",
    ISO2: "IO",
  },
  { country: "Canada", slug: "canada", ISO2: "CA" },
  { country: "Turkey", slug: "turkey", ISO2: "TR" },
  {
    country: "Turks and Caicos Islands",
    slug: "turks-and-caicos-islands",
    ISO2: "TC",
  },
  { country: "Uzbekistan", slug: "uzbekistan", ISO2: "UZ" },
  {
    country: "Falkland Islands (Malvinas)",
    slug: "falkland-islands-malvinas",
    ISO2: "FK",
  },
  { country: "Malta", slug: "malta", ISO2: "MT" },
  { country: "Seychelles", slug: "seychelles", ISO2: "SC" },
  { country: "Andorra", slug: "andorra", ISO2: "AD" },
  { country: "Belgium", slug: "belgium", ISO2: "BE" },
  { country: "Bhutan", slug: "bhutan", ISO2: "BT" },
  { country: "Greece", slug: "greece", ISO2: "GR" },
  { country: "Nauru", slug: "nauru", ISO2: "NR" },
  { country: "Denmark", slug: "denmark", ISO2: "DK" },
  { country: "Netherlands", slug: "netherlands", ISO2: "NL" },
  { country: "South Sudan", slug: "south-sudan", ISO2: "SS" },
  { country: "Thailand", slug: "thailand", ISO2: "TH" },
  { country: "Brazil", slug: "brazil", ISO2: "BR" },
  { country: "Cameroon", slug: "cameroon", ISO2: "CM" },
  { country: "Jersey", slug: "jersey", ISO2: "JE" },
  { country: "Korea (South)", slug: "korea-south", ISO2: "KR" },
  { country: "Netherlands Antilles", slug: "netherlands-antilles", ISO2: "AN" },
  { country: "Portugal", slug: "portugal", ISO2: "PT" },
  { country: "Egypt", slug: "egypt", ISO2: "EG" },
  { country: "Hungary", slug: "hungary", ISO2: "HU" },
  { country: "Paraguay", slug: "paraguay", ISO2: "PY" },
  { country: "Saint Helena", slug: "saint-helena", ISO2: "SH" },
  { country: "South Africa", slug: "south-africa", ISO2: "ZA" },
  { country: "Guatemala", slug: "guatemala", ISO2: "GT" },
  { country: "Mauritania", slug: "mauritania", ISO2: "MR" },
  { country: "Mongolia", slug: "mongolia", ISO2: "MN" },
  { country: "Antarctica", slug: "antarctica", ISO2: "AQ" },
  { country: "Kiribati", slug: "kiribati", ISO2: "KI" },
  { country: "Mozambique", slug: "mozambique", ISO2: "MZ" },
  { country: "Croatia", slug: "croatia", ISO2: "HR" },
  { country: "Malawi", slug: "malawi", ISO2: "MW" },
  { country: "Albania", slug: "albania", ISO2: "AL" },
  { country: "Italy", slug: "italy", ISO2: "IT" },
  { country: "Nepal", slug: "nepal", ISO2: "NP" },
];
